---
- name: Install Apache web server
  apt:
    name: apache2
    state: present

- name: Enable Apache web server
  service:
    name: apache2
    enabled: true
    state: started
    
- name: Change default landing page
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
    owner: root
    group: root

