---
- name: Install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_9.4.3_amd64.deb
  become: true

- name: Start grafana service
  service:
    name: grafana-server
    state: started
    enabled: true
  become: true
